fix(.github): passing global env variables to docker-compose

diff --git a/.github/workflows/awesome_development.yml b/.github/workflows/awesome_development.yml
--- a/.github/workflows/awesome_development.yml
+++ b/.github/workflows/awesome_development.yml
@@ -76,15 +76,15 @@ jobs:
           EOF
           echo notes_service/config/development.env has created successfully
 
-          cat > config/development.env <<EOF
-          ENVIRONMENT=development
-          RABBITMQ_DEFAULT_USER=${{secrets.DEV_AUTH_RABBITMQ_USER}}
-          RABBITMQ_DEFAULT_PASS=${{secrets.DEV_AUTH_RABBITMQ_PASSWORD}}
-          REDIS_USER=${{secrets.DEV_AUTH_REDIS_USER}}
-          REDIS_USER_PASSWORD=${{secrets.DEV_AUTH_REDIS_USER_PASSWORD}}
-          REDIS_PASSWORD=${{secrets.DEV_AUTH_REDIS_PASSWORD}}
-          EOF
-          echo config/development.env has created successfully
+          # cat > config/development.env <<EOF
+          # ENVIRONMENT=development
+          # RABBITMQ_DEFAULT_USER=${{secrets.DEV_AUTH_RABBITMQ_USER}}
+          # RABBITMQ_DEFAULT_PASS=${{secrets.DEV_AUTH_RABBITMQ_PASSWORD}}
+          # REDIS_USER=${{secrets.DEV_AUTH_REDIS_USER}}
+          # REDIS_USER_PASSWORD=${{secrets.DEV_AUTH_REDIS_USER_PASSWORD}}
+          # REDIS_PASSWORD=${{secrets.DEV_AUTH_REDIS_PASSWORD}}
+          # EOF
+          # echo config/development.env has created successfully
       - name: Validate .env files
         run: |
           # Check for missing required variables auth_service/.env
@@ -127,25 +127,24 @@ jobs:
             fi
           done
           
-          # Check for missing required variables config/development.env
-          if [ ! -f config/development.env ]; then
-            echo "Env file config/development.env is missing"
-            exit 1
-          fi
-          GLOBAL_REQUIRED_VARS=("RABBITMQ_DEFAULT_USER RABBITMQ_DEFAULT_PASS REDIS_USER REDIS_USER_PASSWORD REDIS_PASSWORD") 
-          for var in $GLOBAL_REQUIRED_VARS; do
-            if ! grep -qE "^$var=.+$" config/development.env; then
-              echo "Error: Missing required variable $var in config/development.env"
-              exit 1
-            fi
-          done
+          # # Check for missing required variables config/development.env
+          # if [ ! -f config/development.env ]; then
+          #   echo "Env file config/development.env is missing"
+          #   exit 1
+          # fi
+          # GLOBAL_REQUIRED_VARS=("RABBITMQ_DEFAULT_USER RABBITMQ_DEFAULT_PASS REDIS_USER REDIS_USER_PASSWORD REDIS_PASSWORD") 
+          # for var in $GLOBAL_REQUIRED_VARS; do
+          #   if ! grep -qE "^$var=.+$" config/development.env; then
+          #     echo "Error: Missing required variable $var in config/development.env"
+          #     exit 1
+          #   fi
+          # done
       - name: Set up docker compose
         uses: docker/setup-compose-action@v1
         
       - name: Run docker compose directly
         run: |
-            cat ./config/development.env
-            docker compose --env-file ./config/development.env up --build -d
+            docker compose up --build -d
 
             docker container ls
             
@@ -155,4 +154,12 @@ jobs:
             docker compose exec user-service-http /bin/sh env
             echo notes env 
             docker compose exec notes-service-http /bin/sh env
+        env:
+          ENVIRONMENT=development
+          RABBITMQ_DEFAULT_USER=${{secrets.DEV_AUTH_POSTGRES_USER}}
+          RABBITMQ_DEFAULT_PASS=${{secrets.DEV_AUTH_POSTGRES_PASSWORD}}
+          REDIS_USER=${{secrets.DEV_AUTH_REDIS_USER}}
+          REDIS_USER_PASSWORD=${{secrets.DEV_AUTH_REDIS_USER_PASSWORD}}
+          REDIS_PASSWORD=${{secrets.DEV_AUTH_REDIS_PASSWORD}}
+
 
